// Optional macOS verification only; never imports into Photos.
import Foundation
import AVFoundation
import ImageIO
import Photos
import AppKit
import UniformTypeIdentifiers

struct Failure: Error, CustomStringConvertible { let description: String }
func check(_ ok: Bool, _ message: String) throws { if !ok { throw Failure(description: message) } }
func writeJSON(_ object: [String: Any], _ url: URL) throws {
    try JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .sortedKeys]).write(to: url)
}
func run() throws {
    let args = CommandLine.arguments
    try check(args.count == 2, "Usage: verify_live_photo PAIR_DIRECTORY")
    let output = URL(fileURLWithPath: args[1], isDirectory: true)
    let manifestURL = output.appendingPathComponent("manifest.json")
    guard var manifest = try JSONSerialization.jsonObject(with: Data(contentsOf: manifestURL)) as? [String: Any],
          let identifier = manifest["identifier"] as? String,
          let seconds = manifest["coverTime"] as? Double,
          let fps = manifest["fps"] as? Double,
          let photo = manifest["photo"] as? String,
          let video = manifest["video"] as? String else { throw Failure(description: "Invalid manifest") }
    try check(seconds.isFinite && seconds >= 0 && fps.isFinite && fps > 0, "Invalid time/fps")
    let imageURL = output.appendingPathComponent(photo)
    let videoURL = output.appendingPathComponent(video)
    manifest["localPHLivePhotoLoad"] = "failed"
    manifest["loadError"] = "Apple verification did not complete; inspect command diagnostics"
    try writeJSON(manifest, manifestURL)
    // Independent Apple framework readback of files generated by either backend.
    guard let imageCheck = CGImageSourceCreateWithURL(imageURL as CFURL, nil) else { throw Failure(description: "Invalid image") }
    let imageProps = CGImageSourceCopyPropertiesAtIndex(imageCheck, 0, nil) as? [String: Any]
    let imageID = (imageProps?[kCGImagePropertyMakerAppleDictionary as String] as? [String: Any])?["17"] as? String
    let paired = AVURLAsset(url: videoURL)
    let videoID = paired.metadata(forFormat: .quickTimeMetadata).first { $0.identifier == .quickTimeMetadataContentIdentifier }?.stringValue
    try check(imageID == identifier && videoID == identifier, "Readback identifier mismatch")
    var actualTime: Double?
    for metadataTrack in paired.tracks(withMediaType: .metadata) {
        let mr = try AVAssetReader(asset: paired)
        let mo = AVAssetReaderTrackOutput(track: metadataTrack, outputSettings: nil)
        mr.add(mo)
        let ma = AVAssetReaderOutputMetadataAdaptor(assetReaderTrackOutput: mo)
        try check(mr.startReading(), "Metadata readback failed")
        while let group = ma.nextTimedMetadataGroup() {
            if group.items.contains(where: { $0.key as? String == "com.apple.quicktime.still-image-time" }) {
                actualTime = CMTimeGetSeconds(group.timeRange.start)
            }
        }
        try check(mr.status == .completed, "Incomplete metadata readback")
    }
    try check(actualTime != nil && abs(actualTime!-seconds) < 1/fps, "Still time missing or incorrect")
    var loaded = false, completed = false, loadError: String?
    let request = PHLivePhoto.request(withResourceFileURLs: [imageURL, videoURL], placeholderImage: nil, targetSize: .zero, contentMode: .aspectFit) { live, info in
        if (info[PHLivePhotoInfoIsDegradedKey] as? Bool) == true { return }
        loaded = live != nil
        loadError = (info[PHLivePhotoInfoErrorKey] as? Error)?.localizedDescription
        completed = true
    }
    let deadline = Date().addingTimeInterval(30)
    while !completed && Date() < deadline { RunLoop.current.run(until: Date().addingTimeInterval(0.05)) }
    if !completed { PHLivePhoto.cancelRequest(withRequestID: request); loadError = "PHLivePhoto loading timed out" }
    manifest["localPHLivePhotoLoad"] = loaded ? "passed" : "failed"
    manifest["loadError"] = loadError ?? ""
    manifest.removeValue(forKey: "localLoadReason")
    manifest["appleReadbackStillTime"] = actualTime!
    try writeJSON(manifest, manifestURL)
    print("Apple identifiers and timed metadata verified; PHLivePhoto: \(loaded ? "passed" : "failed")")
    try check(loaded, "PHLivePhoto failed: \(loadError ?? "unknown")")
}
do { try run() } catch { fputs("LiveCanvas: \(error)\n", stderr); exit(1) }
